### PR TITLE
Added a Chinese version

### PR DESCRIPTION
**Pull request by gzliyu**

### CODE REVIEW

**Comment by gzliyu** [comment]
Hi! This commit relates to issue#24. I translated parts of the descriptions into Chinese. Please let me know if I am doing this correctly.

**Comment by lunaroyster** [comment]
Hey! Thanks a lot for your contribution! This will definitely help a lot of people! I'll make sure to merge it this week.

You can try out the app here in the meanwhile, to make sure it works as expected: https://deploy-preview-25--latexsearch.netlify.app/

**Comment by lunaroyster** [comment]
Sweet! I'll merge it to master this weekend. We'll load the Chinese version if the user has zh-* enabled on their browser

Thanks again!

**Comment by lunaroyster** [comment]
Okay, I merged to master. If a user has `zh` or `zh-CN` available in `window.navigator.languages`, we search and display the Chinese descriptions.

**Pull request merged**
